version: "3"
services:
  app:
    build: ./
    command: sh -c "yarn run dev"
    container_name: "Portfolio_Frontend"
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    stdin_open: true
    tty: true
  db:
    image: postgres:15.1
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nextjs-sample
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
volumes:
  postgres:
# rails と 連携する場合はコメントアウトを外す
#     networks:
#       external-network:
#         ipv4_address: 192.168.192.2
# networks:
#   external-network:
#     external: true
